locales/locales.go, locales/locales_test.go
本地化包中的`v.AddTranslates` ，应替换为`v.AddMessages`，使用起来会更加友好
根据包中的定义`AddTranslates`用来自定义翻译验证字段名称，而`AddMessages`用来翻译错误信息会比较合适
而目前使用的`AddTranslates`使用后，验证字段名称依然是非本地化语言，如果定义则会覆盖本地化包定义默认错误信息，而换`AddMessages`后，只定义验证字段名称即可，大概意思查看代码
=> 使用AddMessages代替AddTranslates

filtering_test.go, helper.go
nil don't has any interface type and any dynamic type or value => reflect.ValueOf(nil).Kind() == reflect.Invalid and reflect.Call with reflect.Invalid parameter emit panic 
This problem very critical as any custom filtered field with nil pulled variable can cause panic recovery of server or even crash of it.
Signed-off-by: d7561985 <d7561985@gmail.com>
=> EMERGE: Fix panic in custom filter call because of nil variable check.

README.md, README.zh-CN.md, helper.go, locales/locales.go, messages.go, validate.go, validate_test.go, validation.go, validator_alias.go, validators.go, validators_test.go
添加以下方法：
required_if:anotherfield,value,...
如果其它字段 _anotherfield_ 为任一值 _value_ ，则此验证字段必须存在且不为空。
required_unless:anotherfield,value,...
如果其它字段 _anotherfield_ 不等于任一值 _value_ ，则此验证字段必须存在且不为空。
required_with:foo,bar,...
在其他任一指定字段出现时，验证的字段才必须存在且不为空。
required_with_all:foo,bar,...
只有在其他指定字段全部出现时，验证的字段才必须存在且不为空。
required_without:foo,bar,...
在其他指定任一字段不出现时，验证的字段才必须存在且不为空。
required_without_all:foo,bar,...
只有在其他指定字段全部不出现时，验证的字段才必须存在且不为空。
=> 1.1.x - add requiredXXX validators

validate.go, validation_test.go
The [logic](https://github.com/gookit/validate/blob/master/validate.go#L337) to check if a request contains JSON is too restrictive. Since only the exact `application/json` string is considered valid, when the `Content-Type` header contains values such as `application/vnd.api+json` or `application/json; charset=UTF-8`, the request body is dismissed.
Another problem is that there are other JSON MIME types besides `application/json`.
If we do a quick search [here](https://www.iana.org/assignments/media-types/media-types.xhtml), we can find 200+ MIME types related to JSON.
The mime type check logic has been improved by using a regular expression. Here's a brief explanation:
```
(?i)  --> case insensitive matches
application/ --> the only type we care about and the type/subtype separator …
```
=> [FIX] FromRequest() JSON content type validation

data_source.go, data_source_test.go, messages.go, validate.go, validation.go
Validate. Errors supports specifying output fields  #103
=> Supports specifying output fields

data_source.go, messages.go
I was trying out the filter feature today on a struct, but made a mistake and did not pass the struct by reference/pointer:
```
type Foo struct {
A string `filter:"trim"`
}
func main() {
foo := Foo{A: "    test     "}
v := validate.Struct(foo)
if !v.Validate() {
fmt.Println(v.Errors.String())
}
}
```
It took me a little while to figure out the problem because the error message was not very clear:
```
_filter:
_filter: set value failure
```
This MR improves the error message to be more informative. Hopefully it helps others debug easier :)
=> improve error message for filter pass-by-value

.github/workflows/go.yml, .golangci.yml, data_source.go, filtering.go, issues_test.go, messages.go, rule.go, util.go, util_test.go, validate.go, validate_test.go, validating.go, validation.go, validation_test.go, validators.go, validators_test.go, value.go
Add golangci-lint linter with github action
Not many changes :) 
Some unused/ineffectual code, and some slice preallocation optimisations.
Sorry that lots of the comments got reformatted, I think this is because of [new Go 1.19 docstrings](https://tip.golang.org/doc/comment).
=> add golangci-lint linter

issues_test.go, validating.go, validation.go
Right now, the system only allows to  use `tags.*` for slices, but if the slice is a complex type(struct or map) there is no way to validate.
This commits adds a way to test inside slice content if the value is a map:
```
var data = map[string]interface{}{
"user": "foo",
"properties": []map[string]string{{
"phone": "12001",
"alias": "foobar",
}},
}
v := validate.Map(data)
v.ConfigRules(map[string]string{
"properties.*.phone": "int",
"properties.*.alias": "minlen:4",
})
```
Added tests inside a current test, I thought that makes sense to have in there.
Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>
=> feat: enable slices of maps on structs

data_source.go, validate_test.go
Fix https://github.com/gookit/validate/issues/182 to correctly parse the name from the json tag, or ignore it and use the struct field's name instead if it is not set.
=> fix: correctly parse json tag name

data_source.go, issues_test.go, validation.go
This fixes https://github.com/gookit/validate/issues/188 
1. Fix the fact that embedded struct pointers were not validated. 
* This was because of the `if fValue.Type().Kind() == reflect.Ptr && fValue.IsNil()` skip
* To make this work, a different check `removeValuePtr(vv).IsValid()` is used.
2. Allow scenes field rules to apply to child fields.
For example, in my test case, I can add `Settings.Pet` for a validator scene, and it will apply the rules for `Settings.Pet.Breed` and `Settings.Pet.Color`, so I do not have to list every single field.
=> fix: validation for embedded structs

validating.go
Enhanced the validation logic to handle pointer fields more robustly. Previously, the validation would fail when a field was a pointer type but the validation function expected a non-pointer type. The changes include dereferencing the pointer before validation if the validation function does not expect a pointer, and adding a nil check before dereferencing. This makes the validation logic more robust and flexible, allowing for better handling of pointer and non-pointer fields.
Fix #236
=> Improve validation of pointer fields

data_source.go
This pull request addresses the panic encountered when the `gookit/validate` library attempts to validate a struct that contains a nil pointer to a slice field, as reported in issue #252.
**Problem**:
When validating a struct with a field that is a nil pointer to a slice, the library would panic with an error message: `reflect: call of reflect.Value.Len on zero Value`. This is due to a call to `Len()` without first checking if the `reflect.Value` is valid and not nil.
**Solution**:
The proposed fix introduces a check that ensures the `reflect.Value` is valid and not nil before any call to `Len()`. This prevents the panic by safely handling nil pointers as if they point to empty slices, which aligns with the expected behavior of the validation library.
**Example**:
The issue can be …
=> fix: Prevent panic on validating nil pointer to slice field (#252)

data_source.go
This pull request addresses a issue within the `gookit/validate` library where attempting to validate a struct containing a nil pointer to a map field results in a runtime panic.
**Problem:**
The library encounters a panic with the error message: `reflect: call of reflect.Value.MapKeys on zero Value`, when it attempts to validate a struct field that is a nil pointer to a map. This occurs due to the invocation of `MapKeys()` without prior validation of the `reflect.Value` being both non-nil and valid.
**Solution:**
A safeguard has been implemented to check that the `reflect.Value` is not nil and is valid before any call to `MapKeys()`. This modification ensures graceful handling of nil pointer fields, treating them as empty maps, which is the anticipated behavior for such cases in the …
=> Fix: Prevent panic when validating struct with nil pointer to map field

README.md, _examples/httpdemo2/main.go
Yesterday I tried to use a custom filter but couldn't get it to work. I looked in the documentation and example code but found no information about this, so I read the source code and figured out that I had to call the `FilterRule` method. Upon reflection, this design makes sense and feels natural but I think it would be good to have an example in the readme.
1. Add a `FilterRule` call in the readme's `Add Custom Filter` section.
2. Uncomment a line in the example code, making the usage of the custom filter more obvious.
=> [Doc] Add code example of how to use custom filters

data_source.go, data_source_test.go, validators.go, validators_test.go
close https://github.com/gookit/validate/issues/286
```go
v := validate.New(map[string][]string{
"date": {"2023-03", "2023-04"},
})
v.StringRule("date", "required|array|len:2")
v.StringRule("date.*", "required|date:2006-01")
if v.Validate() {
fmt.Println(v.SafeData())
} else {
fmt.Println(v.Errors)
}
```
Print:
```bash
map[date:[2023-03 2023-04] date.*:[2023-03 2023-04]]
```
=> feat: support validation of array values in URL query parameters

data_source.go, data_source_test.go
close https://github.com/gookit/validate/issues/227
```go
type UserForm struct {
Name string                  `validate:"required"`
File []*multipart.FileHeader `validate:"required"`
}
data, err := validate.FromRequest(ctx.Request().Origin())
if err != nil {
panic(err)
}
v := data.Create()
v.AddRule("name", "required")
v.AddRule("file", "required")
if v.Validate() { // validate ok
// safeData := v.SafeData()
userForm := &UserForm{}
if err := v.BindSafeData(userForm); err != nil {
panic(err)
}
// do something ...
for k, v := range userForm.File {
fmt.Println(k, "=====", v.Filename)
}
} else {
fmt.Println(v.Errors)       // all error messages
fmt.Println(v.Errors.One()) // returns a random error message text
}
```
```bash
curl --location 'http://127.0.0.1:3000/files' \
--form 'name="test"' …
```
=> feat: support multi multipart.FileHeader binding

data_source.go, data_source_test.go, validation_test.go
In reflection-based validation we were force‑casting map values to string, which panicked if the key wasn’t a raw string but a named string:
`val = strings.ReplaceAll(val.(string), "\"", "") //nolint:forcetypeassert`
By switching to `key.String()`, we obtain the textual form of any named string key without a type assertion.
=> Fix: prevent panic when using named string types as map keys

validate.go, validate_test.go
This pull request introduces a new global option to control whether the HTTP request body should be automatically restored after being read. This enhancement increases the flexibility of the validation process by allowing users to enable or disable request body restoration, ensuring that the body remains available for further processing by subsequent middleware or handlers.
**Key Changes:**
- Adds a configurable global option for restoring the request body after validation.
- Improves compatibility with middleware and custom logic that may require access to the original request body.
- Provides users with fine-grained control over request lifecycle management.
This update addresses [goravel/goravel Issue #334](https://github.com/goravel/goravel/issues/334).
=> feat: add option to restore request body after reading

util.go, validate_test.go, validating.go, validators.go
close https://github.com/gookit/validate/issues/294
This change unifies all type conversions for validation arguments through `convTypeByBaseKind`, leveraging `reflects.ConvToKind` internally.
As a result, custom types—including `github.com/google/uuid.UUID`—are now correctly coerced to string when they implement `fmt.Stringer`.
This allows the uuid validator to validate google/uuid.UUID fields without error, resolving issue #294.
=> fix: support validation of google/uuid.UUID type

data_source.go, issues_test.go
close https://github.com/gookit/validate/issues/297
close https://github.com/gookit/validate/issues/282
- Error keys now correctly use full JSON tag paths in nested arrays and structs.
- Resolves issue where error keys were missing JSON tags, e.g., "extras.0.github" instead of "github".
=> fix: preserve nested JSON tag paths in error keys

issues_test.go, rule.go, util.go
close https://github.com/gookit/validate/issues/301
This PR addresses an issue with parsing validation rules that contain escaped pipe (`|`) characters, particularly relevant for regex rules in the validation library. The key changes involve introducing a new function to correctly split rule strings, updating the rule parsing logic to use this function, and adding a test to verify the fix.
**Rule Parsing Improvements:**
* Added a new `splitRules` function in `util.go` to correctly split rule strings on unescaped pipe (`|`) characters, ensuring that pipes within regex patterns are not treated as rule separators.
* Updated the `StringRule` method in `rule.go` to use the new `splitRules` function instead of a basic string split, improving support for complex rule definitions.
**Testing:**
* …
=> fix: support escaped "|" in regex validation rules
